# Generated by Django 2.2.12 on 2020-12-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30, verbose_name='种类名称')),
                ('class_img', models.ImageField(upload_to='', verbose_name='种类图片')),
            ],
        ),
        migrations.CreateModel(
            name='SPUProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPU_name', models.CharField(max_length=30, verbose_name='SPU名称')),
                ('SPU_info', models.TextField(verbose_name='SPU详情')),
            ],
        ),
        migrations.CreateModel(
            name='CmdtProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdt_name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('cmdt_prof', models.TextField(verbose_name='商品简介')),
                ('cmdt_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('cmdt_unit', models.CharField(max_length=10, verbose_name='商品单位')),
                ('cmdt_stock', models.IntegerField(verbose_name='商品库存')),
                ('cmdt_status', models.IntegerField(verbose_name='商品状态')),
                ('cmdt_imgurl', models.CharField(max_length=1000, verbose_name='图片链接')),
                ('SPU_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdt.SPUProfile')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdt.ClassProfile')),
            ],
        ),
    ]
