# Generated by Django 2.2.12 on 2020-12-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdtimgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=1000, verbose_name='商品图片')),
                ('cmdt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdt.CmdtProfile')),
            ],
        ),
    ]
