# Generated by Django 2.2.12 on 2020-12-30 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdt', '0002_cmdtimgprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdtdisplayProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displaysign', models.CharField(max_length=1000, verbose_name='主页展示标识')),
                ('SPU_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdt.SPUProfile')),
                ('cmdt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdt.CmdtProfile')),
            ],
        ),
        migrations.CreateModel(
            name='BannerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerimgurl', models.CharField(max_length=1000, verbose_name='轮播图片')),
                ('bannerindex', models.IntegerField(verbose_name='显示顺序')),
                ('cmdt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdt.CmdtProfile')),
            ],
        ),
    ]
