# Generated by Django 2.2.12 on 2020-12-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmdt_orderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_order', models.IntegerField(verbose_name='订单商品数量')),
                ('price_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单商品价格')),
                ('comment', models.TextField(verbose_name='评论')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderProfile')),
            ],
        ),
    ]
